FontSizeBase: 0
FontScaleMain: 1
FontScaleDpi: 1
Alpha: 1
DisabledAlpha: 0.6
WindowPadding:
  - 10
  - 8
WindowRounding: 8
WindowBorderSize: 1
WindowBorderHoverPadding: 4
WindowMinSize:
  - 32
  - 32
WindowTitleAlign:
  - 0.5
  - 0.5
WindowMenuButtonPosition: Left
ChildRounding: 4
ChildBorderSize: 1
PopupRounding: 6
PopupBorderSize: 1
FramePadding:
  - 6
  - 4
FrameRounding: 6
FrameBorderSize: 1
ItemSpacing:
  - 8
  - 6
ItemInnerSpacing:
  - 6
  - 4
CellPadding:
  - 4
  - 2
TouchExtraPadding:
  - 0
  - 0
IndentSpacing: 21
ColumnsMinSpacing: 6
ScrollbarSize: 14
ScrollbarRounding: 6
ScrollbarPadding: 2
GrabMinSize: 12
GrabRounding: 6
LogSliderDeadzone: 4
ImageRounding: 0
ImageBorderSize: 0
TabRounding: 8
TabBorderSize: 0
TabMinWidthBase: 1
TabMinWidthShrink: 80
TabCloseButtonMinWidthSelected: -1
TabCloseButtonMinWidthUnselected: 0
TabBarBorderSize: 1
TabBarOverlineSize: 1
TableAngledHeadersAngle: 0.61086524
TableAngledHeadersTextAlign:
  - 0.5
  - 0
TreeLinesFlags: 262144
TreeLinesSize: 1
TreeLinesRounding: 0
DragDropTargetRounding: 0
DragDropTargetBorderSize: 2
DragDropTargetPadding: 3
ColorMarkerSize: 3
ColorButtonPosition: Right
ButtonTextAlign:
  - 0.5
  - 0.5
SelectableTextAlign:
  - 0
  - 0
SeparatorSize: 1
SeparatorTextBorderSize: 3
SeparatorTextAlign:
  - 0
  - 0.5
SeparatorTextPadding:
  - 20
  - 3
DisplayWindowPadding:
  - 19
  - 19
DisplaySafeAreaPadding:
  - 3
  - 3
MouseCursorScale: 1
AntiAliasedLines: true
AntiAliasedLinesUseTex: true
AntiAliasedFill: true
CurveTessellationTol: 1.25
CircleTessellationMaxError: 0.3
HoverStationaryDelay: 0.15
HoverDelayShort: 0.15
HoverDelayNormal: 0.4
HoverFlagsForTooltipMouse: 41984
HoverFlagsForTooltipNav: 197632
_MainScale: 1
_NextFrameFontSizeBase: 0
Colors:
  Text:
    - 0.96
    - 0.94
    - 0.9
    - 1
  TextDisabled:
    - 0.65
    - 0.62
    - 0.58
    - 1
  WindowBg:
    - 0.2
    - 0.18
    - 0.16
    - 1
  ChildBg:
    - 0.22
    - 0.2
    - 0.18
    - 1
  PopupBg:
    - 0.24
    - 0.22
    - 0.2
    - 1
  Border:
    - 0.58
    - 0.54
    - 0.5
    - 1
  BorderShadow:
    - 0.08
    - 0.06
    - 0.04
    - 0.5
  FrameBg:
    - 0.42
    - 0.39
    - 0.36
    - 1
  FrameBgHovered:
    - 0.5
    - 0.46
    - 0.42
    - 1
  FrameBgActive:
    - 0.58
    - 0.54
    - 0.5
    - 1
  TitleBg:
    - 0.16
    - 0.14
    - 0.12
    - 1
  TitleBgActive:
    - 0.24
    - 0.22
    - 0.2
    - 1
  TitleBgCollapsed:
    - 0.16
    - 0.14
    - 0.12
    - 0.7
  MenuBarBg:
    - 0.18
    - 0.16
    - 0.14
    - 1
  ScrollbarBg:
    - 0.3
    - 0.28
    - 0.26
    - 1
  ScrollbarGrab:
    - 0.55
    - 0.52
    - 0.49
    - 1
  ScrollbarGrabHovered:
    - 0.65
    - 0.62
    - 0.58
    - 1
  ScrollbarGrabActive:
    - 0.75
    - 0.72
    - 0.68
    - 1
  CheckMark:
    - 0.85
    - 0.6
    - 0.7
    - 1
  SliderGrab:
    - 0.8
    - 0.55
    - 0.65
    - 1
  SliderGrabActive:
    - 0.9
    - 0.65
    - 0.75
    - 1
  Button:
    - 0.7
    - 0.45
    - 0.55
    - 1
  ButtonHovered:
    - 0.8
    - 0.55
    - 0.65
    - 1
  ButtonActive:
    - 0.6
    - 0.35
    - 0.45
    - 1
  Header:
    - 0.65
    - 0.5
    - 0.7
    - 0.65
  HeaderHovered:
    - 0.75
    - 0.6
    - 0.8
    - 0.85
  HeaderActive:
    - 0.7
    - 0.55
    - 0.75
    - 0.95
  Separator:
    - 0.55
    - 0.5
    - 0.46
    - 1
  SeparatorHovered:
    - 0.75
    - 0.65
    - 0.6
    - 1
  SeparatorActive:
    - 0.85
    - 0.75
    - 0.7
    - 1
  ResizeGrip:
    - 0.26
    - 0.59
    - 0.98
    - 0.2
  ResizeGripHovered:
    - 0.26
    - 0.59
    - 0.98
    - 0.67
  ResizeGripActive:
    - 0.26
    - 0.59
    - 0.98
    - 0.95
  InputTextCursor:
    - 1
    - 1
    - 1
    - 1
  TabHovered:
    - 0.55
    - 0.4
    - 0.7
    - 1
  Tab:
    - 0.45
    - 0.3
    - 0.6
    - 1
  TabSelected:
    - 0.6
    - 0.45
    - 0.75
    - 1
  TabSelectedOverline:
    - 0.26
    - 0.59
    - 0.98
    - 1
  TabDimmed:
    - 0.4
    - 0.26
    - 0.55
    - 1
  TabDimmedSelected:
    - 0.5
    - 0.35
    - 0.65
    - 1
  TabDimmedSelectedOverline:
    - 0.5
    - 0.5
    - 0.5
    - 0
  PlotLines:
    - 0.8
    - 0.9
    - 0.65
    - 1
  PlotLinesHovered:
    - 0.9
    - 1
    - 0.75
    - 1
  PlotHistogram:
    - 0.85
    - 0.6
    - 0.8
    - 1
  PlotHistogramHovered:
    - 0.95
    - 0.7
    - 0.9
    - 1
  TableHeaderBg:
    - 0.48
    - 0.44
    - 0.4
    - 1
  TableBorderStrong:
    - 0.62
    - 0.58
    - 0.54
    - 1
  TableBorderLight:
    - 0.52
    - 0.48
    - 0.44
    - 1
  TableRowBg:
    - 0.28
    - 0.26
    - 0.24
    - 1
  TableRowBgAlt:
    - 0.32
    - 0.3
    - 0.27
    - 1
  TextLink:
    - 0.26
    - 0.59
    - 0.98
    - 1
  TextSelectedBg:
    - 0.85
    - 0.6
    - 0.75
    - 0.45
  TreeLines:
    - 0.43
    - 0.43
    - 0.5
    - 0.5
  DragDropTarget:
    - 0.85
    - 0.6
    - 0.75
    - 0.8
  DragDropTargetBg:
    - 0
    - 0
    - 0
    - 0
  UnsavedMarker:
    - 1
    - 1
    - 1
    - 1
  NavCursor:
    - 0.75
    - 0.55
    - 0.85
    - 0.8
  NavWindowingHighlight:
    - 0.9
    - 0.7
    - 0.9
    - 0.7
  NavWindowingDimBg:
    - 0.08
    - 0.06
    - 0.04
    - 0.5
  ModalWindowDimBg:
    - 0.08
    - 0.06
    - 0.04
    - 0.6